theme: jekyll-theme-minimal
title: ADMN-RealWorld
description: Embedded Systems Course Final Project
author: Alan Hsieh
email: alanhsiu@ucla.edu
github_username: Alanhsiu
github_repo: Alanhsiu/ECM202A_2025Fall_Project_14