theme: jekyll-theme-minimal
title: ADMN-RealWorld
description: Adaptive Multimodal Deep Network for Real-World RGB-D Gesture Recognition
author: Alan Hsieh
email: alanhsiu@ucla.edu
github: Alanhsiu
linkedin: alanhsiu
github_username: Alanhsiu
github_repo: Alanhsiu/ADMN-RealWorld